site_name: Memory and Architecture
site_author: 'Davesh Shingari'
site_url: 'https://shingaridavesh.github.io/memoryandarchitecture/'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: grey
      accent: lime

markdown_extensions:
  - attr_list

plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/shingaridavesh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/davesh-shingari-68800053/
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.      

copyright: |
  &copy; 2024 <a href="https://github.com/shingaridavesh"  target="_blank" rel="noopener">Davesh Shingari</a>

# Page tree
nav:
  - Home: index.md
  - DDR Types:
    - DDR Types/index.md
    - Pins: DDR Types/Pins.md
    - Training: DDR Types/Training.md
    - Extensions:
      - setup/extensions/index.md
      - Python Markdown: setup/extensions/python-markdown.md
      - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - DDR4:
    - DDR4/index.md
  - DDR5:
    - DDR5/index.md
  - LPDDR4:
    - LPDDR4/index.md
  - LPDDR5:
    - LPDDR5/index.md
